version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "graph-proto"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3b4rmfajlr3k"
s3_prefix = "graph-proto"
region = "us-west-2"
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_IAM CAPABILITY_NAMED_IAM"
image_repositories = []
parameter_overrides = "GitProviderType=\"CodeCommit\" CodeCommitRepositoryName=\"GraphETL\" MainGitBranch=\"main\" SamTemplate=\"template.yaml\" TestingRegion=\"us-east-1\" TestingStackName=\"graph-dev\" TestingPipelineExecutionRole=\"arn:aws:iam::052062741630:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-329XHT2CSV4U\" TestingCloudFormationExecutionRole=\"arn:aws:iam::052062741630:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-FR4EUJD79ORI\" TestingArtifactBucket=\"aws-sam-cli-managed-dev-pipeline-artifactsbucket-1umkl2dpw4xc3\" TestingImageRepository=\"\" ProdRegion=\"us-west-1\" ProdStackName=\"graph-stg\" ProdPipelineExecutionRole=\"arn:aws:iam::052062741630:role/aws-sam-cli-managed-stg-pipe-PipelineExecutionRole-9OIDPKEWIRUF\" ProdCloudFormationExecutionExeRole=\"arn:aws:iam::052062741630:role/aws-sam-cli-managed-stg-p-CloudFormationExecutionR-6ZK5QS5HPMTK\" ProdArtifactBucket=\"aws-sam-cli-managed-stg-pipeline-artifactsbucket-xmnrbvocfvcn\" ProdImageRepository=\"\" CodeStarConnectionArn=\"\" FeatureGitBranch=\"\""
