AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  UploadsStack

  Sample SAM Template for UploadsStack

Parameters:
  VideoProcessingStateMachineArn:
    Type: String

Resources:

  IngestBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
#      BucketName: !Sub "video-ingest-${AWS::AccountId}-${AWS::Region}-${AWS::StackName}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      VersioningConfiguration:
        Status: Enabled

  UploadsDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
#      QueueName: !Sub "uploads-dl-queue-${AWS::AccountId}-${AWS::Region}-${AWS::StackName}"
      SqsManagedSseEnabled: true

  NewUploadHandler:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: upload_handler/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 15
      ReservedConcurrentExecutions: 1
      DeadLetterQueue:
        TargetArn: !GetAtt UploadsDeadLetterQueue.Arn
        Type: SQS
      Architectures:
        - x86_64
      Events:
        NewVideoUpload:
          Type: S3
          Properties:
            Bucket: !Ref IngestBucket
            Events: s3:ObjectCreated:*
      Environment:
        Variables:
          VIDEO_PROCESSING_STEP_FUNCTION_ARN: !Ref VideoProcessingStateMachineArn
      Policies:
        - AWSStepFunctionsFullAccess
